services:
  nginx:
    image: nginx:1.26
    container_name: nginx
    network_mode: host
    restart: unless-stopped
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app:/var/www/html:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
      - /dev/shm:/dev/shm
    command: sh -c 'rm -f /dev/shm/nginx.sock && nginx -g "daemon off;"'
